project:
  type: book  
  output-dir: docs

book:
  title: "Analysis of the Conditions Required for Climate-Change Induced Shark-Lifting Tornados"
  author: "Kyle O'Connor"
  page-footer:
    left: "Copyright 2025, Kyle O'Connor"
  chapters:
    - index.qmd
    - intro.qmd
    - methods_and_results.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - data-documentation.qmd
    - draft-results.qmd
    - AI_Usage_Disclosure.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
    toc-title: "Table of Contents"
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true
    toc-title: "Table of Contents"



