project:
  type: book  
  output-dir: docs

book:
  title: "Business Report: Analysis of Climate Changed Induced Shark-Lifting Tornados"
  author: "Kyle O'Connor"
  page-footer:
    left: "Copyright 2025, Kyle O'Connor"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - draft-exec-summary.qmd
    - AI_Usage_Disclosure.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



