# Discussion

@tbl-shark-ktab is a table of k-Nearest Neighbor classification success rates. This table was used to select a value of k that best classifies tornado locations based on the proximity of sharks, conditioned on both the tornado and shark being located in the buffer. Based on this analysis, k=9 was used as it has a maximum overall success rate of 95.57% after disregarding the initial drop from k=1 to k=4 due to the higher likelihood of an outlier affecting accuracy rates.

@tbl-shark-nnc is a table of classifications for all 8 tornados located within the buffer zone, listed as either "Sharks Present" if sharks were found to be in close proximity to the starting location of the tornado, or "No Sharks Present" if no sharks were close enough. This table shows that every tornado was classified as having "No Sharks Present", with 5/8 having a confidence level fo 100%, while the minimum confidence was still 66.67%, well above chance.

According to author Tom Sherrington, "While it’s not a universal certainty, storms can indeed influence shark distribution and bring them closer to shore due to a complex interplay of environmental factors ... [it’s] important to note that not all shark species respond to storms in the same way. Some species, like bull sharks, are known for their tolerance of brackish water and are more likely to be found closer to shore even under normal conditions. Others, like great white sharks, may venture closer to shore in search of larger prey that have been impacted by the storm" [@sherringtonStormsBringSharks2024]. As noted in @tbl-sharks, the most common species of sharks captured were the Atlantic Sharpnose and the Sandbar, and both species are sensitive to changes caused by tornados and hurricanes. This means that the calculated figure (95.57%) is likely an *underestimation of the true success rate*, given the fact that as a result of environmental conditions, these sharks will move further below the surface and/or away from the tornado.
